# .github/workflows/ci.yml

name: Run Tests

# Run on pushes and pull requests targeting main/master
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    strategy:
      # Test against a recent Node.js version
      matrix:
        node-version: [20.x] # Or your preferred Node version

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # Use npm caching for faster builds
          cache: 'npm' 

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm ci # Use ci for cleaner installs in CI environments

      # 4. Run tests
      - name: Run unit tests
        run: npm test 